apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    instanceID: my-ci-controller
    artifactRepository:
      archiveLogs: true
      s3:
        endpoint: minio.minio:9000
        bucket: argo
        region: us-east-2
        insecure: true
        accessKeySecret:
          name: minio
          key: root-user
        secretKeySecret:
          name: minio
          key: root-password
